export const dom = {
    fileInput: document.getElementById('fileInput'),
    uploadSection: document.getElementById('uploadSection'),
    uploadDropHint: document.getElementById('uploadDropHint'),
    gallery: document.getElementById('gallery'),
    memoryBoard: document.getElementById('memoryBoard'),
    memoryRecentList: document.getElementById('memoryRecentList'),
    memoryTodayList: document.getElementById('memoryTodayList'),
    lightbox: document.getElementById('lightbox'),
    lightboxImg: document.getElementById('lightboxImg'),
    lightboxImgWrap: document.querySelector('.lightbox-img-wrap'),
    closeBtn: document.querySelector('.close'),
    deleteBtn: document.getElementById('deleteBtn'),
    favoriteBtn: document.getElementById('favoriteBtn'),
    submitCommentBtn: document.getElementById('submitComment'),
    commentInput: document.getElementById('commentInput'),
    authorInput: document.getElementById('authorInput'),
    commentsList: document.getElementById('commentsList'),
    searchInput: document.getElementById('searchInput'),
    sortSelect: document.getElementById('sortSelect'),
    contentFilterSelect: document.getElementById('contentFilterSelect'),
    clearSearchBtn: document.getElementById('clearSearchBtn'),
    galleryStatus: document.getElementById('galleryStatus'),
    createGroupBtn: document.getElementById('createGroupBtn'),
    groupNav: document.getElementById('groupNav'),
    groupActions: document.getElementById('groupActions'),
    renameGroupBtn: document.getElementById('renameGroupBtn'),
    deleteGroupBtn: document.getElementById('deleteGroupBtn'),
    searchHint: document.getElementById('searchHint'),
    captionInput: document.getElementById('captionInput'),
    tagsInput: document.getElementById('tagsInput'),
    uploadGroupSelect: document.getElementById('uploadGroupSelect'),
    photoStory: document.getElementById('photoStory'),
    festivalBadge: document.getElementById('festivalBadge'),
    recommendThemeBtn: document.getElementById('recommendThemeBtn'),
    headerKicker: document.getElementById('headerKicker'),
    headerDescription: document.getElementById('headerDescription'),
    headerStats: document.getElementById('headerStats'),
    uploadBtn: document.getElementById('uploadBtn'),
    uploadProgressWrap: document.getElementById('uploadProgressWrap'),
    uploadProgressBar: document.getElementById('uploadProgressBar'),
    uploadProgressText: document.getElementById('uploadProgressText'),
    batchBar: document.getElementById('batchBar'),
    batchDeleteToggleBtn: document.getElementById('batchDeleteToggleBtn'),
    batchCount: document.getElementById('batchCount'),
    batchDeleteBtn: document.getElementById('batchDeleteBtn'),
    batchCancelBtn: document.getElementById('batchCancelBtn'),
    batchSelectAllBtn: document.getElementById('batchSelectAllBtn'),
    batchGroupBtn: document.getElementById('batchGroupBtn'),
    batchCaptionBtn: document.getElementById('batchCaptionBtn'),
    pwdModal: document.getElementById('pwdModal'),
    pwdInput: document.getElementById('pwdInput'),
    pwdError: document.getElementById('pwdError'),
    pwdCancelBtn: document.getElementById('pwdCancelBtn'),
    pwdConfirmBtn: document.getElementById('pwdConfirmBtn'),
    nicknameModal: document.getElementById('nicknameModal'),
    nicknameInput: document.getElementById('nicknameInput'),
    nicknameError: document.getElementById('nicknameError'),
    nicknameConfirmBtn: document.getElementById('nicknameConfirmBtn'),
    userAvatar: document.getElementById('userAvatar'),
    userName: document.getElementById('userName'),
    userEditBtn: document.getElementById('userEditBtn'),
    themeToggleBtn: document.getElementById('themeToggleBtn'),
    themePanelBtn: document.getElementById('themePanelBtn'),
    themeDropdown: document.getElementById('themeDropdown'),
    autoThemeBtn: document.getElementById('autoThemeBtn'),
    applyColorBtn: document.getElementById('applyColorBtn'),
    colorStart: document.getElementById('colorStart'),
    colorEnd: document.getElementById('colorEnd'),
    lightboxPrev: document.getElementById('lightboxPrev'),
    lightboxNext: document.getElementById('lightboxNext'),
    filterBar: document.getElementById('filterBar'),
    editBar: document.getElementById('editBar'),
    editToggleBtn: document.getElementById('editToggleBtn'),
    resetEditBtn: document.getElementById('resetEditBtn'),
    saveEditBtn: document.getElementById('saveEditBtn'),
    dynamicSubtitle: document.getElementById('dynamicSubtitle'),
    themeIcon: document.querySelector('.theme-icon'),
    themePackageBtns: [...document.querySelectorAll('.theme-package-btn')],
    themePresets: [...document.querySelectorAll('.theme-preset')],
    filterBtns: [...document.querySelectorAll('.filter-btn')],
    reactionBtns: [...document.querySelectorAll('.reaction-btn')]
};

export const editSliders = [
    { id: 'editBrightness', valId: 'brightnessVal', key: 'brightness', unit: '%' },
    { id: 'editContrast', valId: 'contrastVal', key: 'contrast', unit: '%' },
    { id: 'editSaturate', valId: 'saturateVal', key: 'saturate', unit: '%' },
    { id: 'editBlur', valId: 'blurVal', key: 'blur', unit: 'px' }
];
